try function catch (err) {console.error(err)}

err.response.status

catch (err => {
  res´ńext(err)  //goes next, but to the error page!
})